language: python
python:
  - "2.7"
  
install:
  - pip install .
  - pip install pylint mypy pytest-cov coveralls

script:
  - pylint pyhap test
  - mypy --ignore-missing-imports pyhap
  - pytest --cov pyhap

after_success:
  - coveralls

notifications:
  email: false